# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
before_script:
  - apt-get update -y 
  - apt-get install clojure

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r resources/public/* public
  artifacts:
    paths:
      - public
  only:
    - master
