# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: clojure:latest

pages:
  stage: deploy
  script:
    - lein install
    - lein cljsbuild once
    - mkdir public
    - cp -r resources/public/* public
  artifacts:
    paths:
      - public
  only:
    - master
